apiVersion: v1
kind: Service
metadata:
  name: jenkins-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: jenkins
  externalTrafficPolicy: Local